"""Add dial in session model

Revision ID: 12ddc02f4cff
Revises: 
Create Date: 2026-07-15 14:23:25.482244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12ddc02f4cff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create dial_in_sessions table
    op.create_table(
        "dial_in_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("coffee_bean_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("goal_type", sa.String(), nullable=True),
        sa.Column("desired_notes", sa.String(), nullable=True),
        sa.Column("preferred_profile", sa.String(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["coffee_bean_id"],
            ["coffee_beans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # Add new relationship to brews
    op.add_column(
        "brews",
        sa.Column(
            "dial_in_session_id",
            sa.Integer(),
            nullable=True
        )
    )

    op.create_foreign_key(
        "fk_brews_dial_in_session",
        "brews",
        "dial_in_sessions",
        ["dial_in_session_id"],
        ["id"],
    )

    # Create a dial-in session for existing coffees
    op.execute("""
        INSERT INTO dial_in_sessions
        (
            coffee_bean_id,
            status,
            goal_type,
            preferred_profile
        )
        SELECT
            id,
            'ACTIVE',
            'DISCOVER_NOTES',
            'Sweet and clear'
        FROM coffee_beans
    """)

    # Link existing brews to their session
    op.execute("""
        UPDATE brews
        SET dial_in_session_id = dial_in_sessions.id
        FROM dial_in_sessions
        WHERE brews.coffee_bean_id = dial_in_sessions.coffee_bean_id
    """)

    # Make the relationship required
    op.alter_column(
        "brews",
        "dial_in_session_id",
        nullable=False
    )

    # Remove old coffee bean relationship
    op.drop_constraint(
        "brews_coffee_bean_id_fkey",
        "brews",
        type_="foreignkey"
    )

    op.drop_column(
        "brews",
        "coffee_bean_id"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brews', sa.Column('coffee_bean_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'brews', type_='foreignkey')
    op.create_foreign_key(op.f('brews_coffee_bean_id_fkey'), 'brews', 'coffee_beans', ['coffee_bean_id'], ['id'])
    op.drop_column('brews', 'dial_in_session_id')
    # ### end Alembic commands ###
