"""add created_at to brews

Revision ID: 3fb76fbc3a27
Revises: 12ddc02f4cff
Create Date: 2026-07-15 17:25:59.091240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fb76fbc3a27'
down_revision: Union[str, Sequence[str], None] = '12ddc02f4cff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brews', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.execute(
        "UPDATE brews SET created_at = NOW() WHERE created_at IS NULL"
    )
    op.alter_column(
        "brews",
        "created_at",
        nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brews', 'created_at')
    # ### end Alembic commands ###
